# Generated by Django 4.2 on 2023-04-21 04:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('0', 'Incidente'), ('1', 'Solicitação de serviço'), ('2', 'Melhorias'), ('3', 'Projetos')], max_length=1, verbose_name='Tipo')),
                ('prioridade', models.CharField(choices=[('0', 'Sem prioridade'), ('1', 'Baixa'), ('2', 'Média'), ('3', 'Alta')], max_length=1, verbose_name='Prioridade')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de abertura')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel_tarefa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsavel_tarefa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
