# Generated by Django 4.2 on 2023-04-21 05:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='observacao',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='situacao',
            field=models.CharField(choices=[('0', 'Backlog'), ('1', 'Backlog da sprint'), ('2', 'Em andamento'), ('3', 'Em teste'), ('4', 'Aguardando aprovação'), ('5', 'Concluída')], default='0', max_length=1, verbose_name='Situação'),
        ),
    ]
