# Generated by Django 4.2 on 2023-04-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0004_remove_tarefa_observacao_observacaotarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de conclusão'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='situacao',
            field=models.CharField(choices=[('0', 'Aberta'), ('1', 'Concluída')], default='0', max_length=1, verbose_name='Situação'),
        ),
    ]
